# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html for more information

# [sncast.myprofile1]                                    # Define a profile name
# url = "http://127.0.0.1:5050/"                         # Url of the RPC provider
# accounts_file = "../account-file"                      # Path to the file with the account data
# account = "mainuser"                                   # Account from `accounts_file` or default account file that will be used for the transactions
# keystore = "~/keystore"                                # Path to the keystore file
# wait_params = { timeout = 500, retry_interval = 10 }   # Wait for submitted transaction parameters
# block_explorer = "StarkScan"                           # Block explorer service used to display links to transaction details

[sncast.braavos]                                        # Define a profile name
url = "https://starknet-mainnet.blastapi.io/96de002f-90e7-45f5-b93e-e713f80a22ac/rpc/v0_7"                          # Url of the RPC provider
accounts_file = "/Users/oche/.starknet_accounts/starknet_open_zeppelin_accounts.json"                       # Path to the file with the account data
account = "braavos"                                    # Account from `accounts_file` or default account file that will be used for the transactions                              # Path to the keystore file
wait_params = { timeout = 500, retry_interval = 10 }    # Wait for submitted transaction parameters
block_explorer = "StarkScan"      